"""
AI Shorts Factory - 定数定義

プロジェクト全体で使用する定数を一元管理
"""

# === API関連 ===

# リトライ設定
DEFAULT_MAX_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_MIN_WAIT = 1.0
DEFAULT_RETRY_MAX_WAIT = 10.0

# HTTPステータスコード（リトライ対象）
RETRYABLE_STATUS_CODES = {429, 500, 502, 503, 504}


# === 動画関連 ===

# YouTube Shorts要件
YOUTUBE_SHORTS_MAX_DURATION = 60  # 秒
YOUTUBE_SHORTS_MIN_DURATION = 15  # 秒
YOUTUBE_SHORTS_ASPECT_RATIO = 9 / 16  # 縦長

# 動画デフォルト設定
DEFAULT_VIDEO_WIDTH = 1080
DEFAULT_VIDEO_HEIGHT = 1920
DEFAULT_VIDEO_FPS = 30

# 字幕設定
SUBTITLE_MARGIN_BOTTOM = 250
SUBTITLE_FONT_SIZE = 48
SUBTITLE_PADDING = 100
SUBTITLE_STROKE_WIDTH = 3


# === 画像関連 ===

# FLUX.1の制限
FLUX_MAX_WIDTH = 1024
FLUX_MAX_HEIGHT = 1024

# 画像デフォルト設定
DEFAULT_IMAGE_WIDTH = 1080
DEFAULT_IMAGE_HEIGHT = 1920


# === 音声関連 ===

# VOICEVOX設定
DEFAULT_VOICEVOX_SPEAKER_ID = 3  # ずんだもん
DEFAULT_VOICEVOX_SPEED = 1.0
DEFAULT_VOICEVOX_PITCH = 0.0
DEFAULT_VOICEVOX_INTONATION = 1.0
DEFAULT_VOICEVOX_VOLUME = 1.0


# === ファイル関連 ===

# 一時ファイルの有効期限
TEMP_FILE_MAX_AGE_HOURS = 24

# ファイルパーミッション
SECURE_FILE_PERMISSION = 0o600  # 所有者のみ読み書き可能


# === YouTubeカテゴリID ===

YOUTUBE_CATEGORY_FILM = "1"
YOUTUBE_CATEGORY_AUTOS = "2"
YOUTUBE_CATEGORY_MUSIC = "10"
YOUTUBE_CATEGORY_PETS = "15"
YOUTUBE_CATEGORY_SPORTS = "17"
YOUTUBE_CATEGORY_GAMING = "20"
YOUTUBE_CATEGORY_PEOPLE_BLOGS = "22"  # デフォルト
YOUTUBE_CATEGORY_COMEDY = "23"
YOUTUBE_CATEGORY_ENTERTAINMENT = "24"
YOUTUBE_CATEGORY_NEWS = "25"
YOUTUBE_CATEGORY_HOWTO = "26"
YOUTUBE_CATEGORY_EDUCATION = "27"
YOUTUBE_CATEGORY_SCIENCE = "28"
YOUTUBE_CATEGORY_NONPROFITS = "29"
